livery = {
	{"Material",	DIFFUSE			,	"9S32Radar", true};
	{"Material.017",	DIFFUSE			,	"9M83", true};
	{"Material.010",	DIFFUSE			,	"9M83", true};
	{"Material.002",	DIFFUSE			,	"9M83", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.007",	DIFFUSE			,	"9M83", true};
	{"Material.017",	DIFFUSE			,	"9M83", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.018",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.016",	DIFFUSE			,	"S-300_Shine", true};
	{"Material.008",	DIFFUSE			,	"S-300_Shine", true};
	{"Material.121",	DIFFUSE			,	"9M83", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.015",	DIFFUSE			,	"9M83", true};
	{"Material.024",	DIFFUSE			,	"ERO_forkliftpng", true};
	{"Material.120",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.120",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.120",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.120",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.027",	DIFFUSE			,	"9s32radar", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.022",	DIFFUSE			,	"9M83", true};
	{"Material.011",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.001",	DIFFUSE			,	"9M83", true};
	{"Material.001",	DIFFUSE			,	"9M83", true};
	{"Material.019",	DIFFUSE			,	"9M83", true};
	{"Material.006",	DIFFUSE			,	"9M83", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.122",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.029",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.005",	DIFFUSE			,	"Russian_Camp2-D_ERO", true};
	{"Material.009",	DIFFUSE			,	"glass", true};
}
name = "Desert Camo"